apiVersion: v1
kind: ConfigMap
metadata:
  name: cm01
data:
  URL: example.com
  SUB_URL: sub.example.com
  DOMAIN: .com
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx06
spec:
  containers:
    - name: nginx
      image: nginx
      envFrom:
        - configMapRef:
            name: cm01