apiVersion: v1
kind: Secret
metadata:
  name: secret01
data:
  URL: ZXhhbXBsZS5jb20=
  SUB_URL: c3ViLmV4YW1wbGUuY29t
  DOMAIN: LmNvbQ==
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx07
spec:
  containers:
    - name: nginx
      image: nginx
      envFrom:
        - secretRef:
            name: secret01