apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
      app: nginx
  template:
    metadata:
      labels:
        tier: frontend
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.16
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-cip
spec:
  selector:
    tier: frontend
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
#  annotations:
#    service.beta.kubernetes.io/aws-load-balancer-type: nlb-ip
spec:
  type: LoadBalancer
  selector:
    tier: frontend
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80